name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g newman
    - run: npm install -g newman-reporter-htmlextra
    - run: newman run TCC.postman_collection.json --reporters cli,htmlextra --reporter-htmlextra-export results/Report.html
    
    - name: Step 4 Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
          name: report
          path: results/Report.html
